name: PublishStudentApp

on:
  workflow_dispatch:
  push:
    branches:
      - Release

env:
  AZURE_WEBAPP_NAME: wewain
  AZURE_WEBAPP_PACKAGE_PATH: "./publishPackage"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./StudentServices.sln

      - name: Build
        run: dotnet build ./StudentServices.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./StudentServices.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
